# Virtual env Path - C:\Vignesh\Text2Sql\.venv\Scripts\activate.bat
# uvicorn app.main:app --reload
# List down the materials details of 200X2X12 countply, BPC substrate and G000704 Fibretype
# Mention some recipes for shade EUR09700?    What dyes are used in recipe ID 168?    What threads have a substrate code of 'BPC'?
#
# Show the history of changes for recipe ID 32735.
# What is the total dye concentration for recipe ID 169?
print("\n Workflows called \n")

from text2sql.core.pipeline.events import (
    ClassifyUserQuestionEvent, 
    GeneralResponseEvent,

    TableRetrieveEvent, 
    Text2SQLEvent,
    SampleRetriveEvent,
    SQLFailureEvent,
    SQLCheckEvent,
    PrepEvent,
    ProgressEvent,
    TokenEvent
)
from text2sql.core.retriever import (
    object_retriever, 
    sample_query_retriever, 
    sql_retriever,
    format_nodes_as_table_schema
)
from text2sql.prompts.sql_prompt import (
    SQL_FAILURE_PROMPT,
    TEXT2SQL_PROMPT,
    SQL_FAILURE_PROMPT_TWO
)
from text2sql.prompts.response_prompt import RESPONSE_SYNTHESIS_PROMPT
from text2sql.prompts.general_response_prompt import GENERAL_RESPONSE_PROMPT
from text2sql.prompts.qn_classify_prompt import QUESTION_CLASSIFICATION_PROMPT

from text2sql.core.pipeline.chat_history import(
    load_chat_history,  
    save_chat_history
)

from text2sql.table_context import get_table_context_str
from text2sql.sql_parser import parse_response_to_sql
from text2sql.core.ai_model import llm

from llama_index.core.workflow import (
    Event,
    StartEvent,
    StopEvent,
    Context,
    Workflow,
    step
)
from llama_index.core.memory import ChatMemoryBuffer
from llama_index.core.llms import ChatMessage
import time
import asyncio


# from text2sql.table_context import table_schema_objs/

import asyncio
# import grpc
import sys 

class TextToSQLWorkflow(Workflow):
    def __init__(
            self, 
            obj_retriever, # Retrieves table schemas based on the query.
            sql_retriever, # Executes SQL queries(generated by LLM) on the database.
            sample_retriever, # Retrieves sample SQL queries related to the user's query.
            response_synthesis_prompt, # Prompt for generating the final response.
            sql_failure_prompt , # Prompt for handling SQL query failures
            sql_failure_prompt_two,
            llm, 
            text2sql_prompt, # Prompt for the text-to-SQL conversion.
            query_classification_prompt, # to classify the user question
            general_response_prompt,
            *args, 
            **kwargs
        ):
        
        super().__init__(*args, **kwargs)
        self.obj_retriever = obj_retriever
        self.sql_retriever = sql_retriever
        self.sample_retriever = sample_retriever
        self.response_synthesis_prompt = response_synthesis_prompt
        self.text2sql_prompt = text2sql_prompt
        self.sql_failure_prompt = sql_failure_prompt
        self.sql_failure_prompt_two = sql_failure_prompt_two

        self.query_classification_prompt = query_classification_prompt
        self.general_response_prompt = general_response_prompt

        # to maintain conversation history.
        self.memory = ChatMemoryBuffer.from_defaults(llm=llm) 
        self.llm = llm

    @step 
    async def new_query(self, ctx : Context, ev : StartEvent) -> ClassifyUserQuestionEvent:

        print("\n Given Input Question :", ev.query, "\n")
        
        chat_history = self.memory.get()
        ctx.write_event_to_stream(ProgressEvent(result = "Received Query"))
        
        print("Chat History: ", chat_history)

        # await ctx.set("query", ev.query)
        user_message = ChatMessage(role = "user", content = ev.query)

        self.memory.put(user_message) # Store the User Query in the memory
        
        ctx.write_event_to_stream(ProgressEvent(result = "Retrieving Table Info"))

        return ClassifyUserQuestionEvent(query=ev.query)
    
    # @step
    # async def test_memory(self, ctx : Context, ev : PrepEvent) -> StopEvent:
    #     query = await ctx.get("query")
    #     mess = [ChatMessage(role = "user", content = query)]
    #     response = self.llm.chat(mess)
    #     self.memory.put(ChatMessage(role = "assistant", content = response.message.content))
    #     return StopEvent(result = response)
    

    @step
    async def classify_question(self, ctx : Context, ev : ClassifyUserQuestionEvent) -> PrepEvent | GeneralResponseEvent:

        # Retrieve and format chat history
        chat_history = self.memory.get()    
        chat_history_str = "\n".join([f"{msg.role}: {msg.content}" for msg in chat_history])

        ctx.write_event_to_stream(ProgressEvent(result = "Classifying user query (SQL Qn / General Qn)"))

        # Retrieve table schema
        table_schema_objs = await self.obj_retriever.aretrieve(ev.query)
        table_schema_objs = format_nodes_as_table_schema(table_schema_objs)
        table_context_str = get_table_context_str(table_schema_objs)

        # REtrieve sample queries
        modified_query = ev.query + "\n" + table_context_str
        sample_queries = await self.sample_retriever.aretrieve(modified_query)
        sample_query_str = "\n".join([f" - {sample.text}" for sample in sample_queries])

        fmt_messages = self.query_classification_prompt.format_messages(
            query_str = ev.query,
            schema = table_context_str,
            sample_queries = sample_query_str,
            chat_history_str = chat_history_str
        )

        classification_response = self.llm.chat(fmt_messages)
        classification_response = str(classification_response)[len("assistant: "):].strip()

        print("\n Classification Response :", classification_response, "\n")


        word = "SQL Question"

        # If SQL Query needs to be generated
        if(word in classification_response):
            iteration_number = 0
            return PrepEvent(query = ev.query, iteration_number = iteration_number)
        
        # If user asks a general question
        print("\n General question\n")

        return GeneralResponseEvent( 
            query = ev.query, 
            table_context_str = table_context_str, 
            chat_history_str = chat_history_str
        )
    



    @step
    async def generate_general_response(self, ctx : Context, ev : GeneralResponseEvent) -> StopEvent:
        
        ctx.write_event_to_stream(ProgressEvent(result = "Generating Response (for general question)"))

        fmt_messages = self.general_response_prompt.format_messages(
            query = ev.query,
            sample = ev.table_context_str,
            chat_history_str = ev.chat_history_str
        )

        chat_response = llm.chat(fmt_messages)

        # Store the generated SQL query in memory
        chat_response_str = str(chat_response)[len("assistant: "):].strip()
        self.memory.put(ChatMessage(role = "assistant", content = chat_response_str))   

        return StopEvent(result=chat_response)  


    @step
    async def retrieve_tables(self, ctx : Context, ev : PrepEvent) -> TableRetrieveEvent:

        # table_schema_objs = await self.obj_retriever.aretrieve(ev.query)
        # table_context_str = get_table_context_str(table_schema_objs)

        table_schema_objs = await self.obj_retriever.aretrieve(ev.query)
        table_schema_objs = format_nodes_as_table_schema(table_schema_objs)
        table_context_str = get_table_context_str(table_schema_objs)
        # print("Table Context: ", table_context_str)
        ctx.write_event_to_stream(ProgressEvent(result = "Analyzing Table Schema"))

        return TableRetrieveEvent(
            table_context_str = table_context_str,
            query = ev.query,
            iteration_number = ev.iteration_number
        )
    
    

    @step 
    async def retrieve_samples(self, ctx : Context, ev : TableRetrieveEvent) -> SampleRetriveEvent:

        modified_query = ev.query + "\n" + ev.table_context_str
        sample_queries = await self.sample_retriever.aretrieve(modified_query)

        sample_query_str = "\n".join([f" - {sample.text}" for sample in sample_queries])
        # print("Sample Query String : ", sample_query_str)
        # print("retreived")
        ctx.write_event_to_stream(ProgressEvent(result = "Generating SQL Query"))
        # await asyncio.sleep(0.01)
        # print("rtty")
        return SampleRetriveEvent(
            query = ev.query,
            sample_query = sample_query_str,
            table_context_str = ev.table_context_str,
            iteration_number = ev.iteration_number
        )
    


    @step 
    async def generate_sql(self, ctx : Context, ev : SampleRetriveEvent) -> Text2SQLEvent:


        # Retrieve and format chat history
        chat_history = self.memory.get()    
        chat_history_str = "\n".join([f"{msg.role}: {msg.content}" for msg in chat_history])

        fmt_messages = self.text2sql_prompt.format_messages(
            query_str=ev.query,
            schema=ev.table_context_str,
            sample_queries=ev.sample_query,
            chat_history_str = chat_history_str
        )
        
        sql = ""
        # print(fmt_messages[0].content)
        # async for sql 
        chat_response = self.llm.stream_chat(fmt_messages)
        for token in chat_response:
            sql += token.delta
            ctx.write_event_to_stream(TokenEvent(token = token.delta))

        sql = parse_response_to_sql(ChatMessage(content=sql))
        # return StopEvent(result = "Done")
        # await asyncio.sleep(0.01)
        # print("\n Generated SQL Query : ", sql)
        return Text2SQLEvent(
            sql = sql,
            query = ev.query,
            table_context_str = ev.table_context_str,
            iteration_number = ev.iteration_number
        )   



    @step 
    async def generate_sql_response(self, ctx : Context, ev : Text2SQLEvent) -> SQLFailureEvent | StopEvent:

        # print("\n Generated SQL Query : ", ev.sql)
        
        try:# Execute the generated query
            retrieved_rows = await self.sql_retriever.aretrieve(ev.sql)

        except Exception as e:
            ctx.write_event_to_stream(ProgressEvent(result = "Invalid Query Generated (retrying)"))
            return SQLFailureEvent(query = ev.query, error = str(e), sql = ev.sql,
            table_context_str = ev.table_context_str,
            iteration_number = ev.iteration_number)

        # Store the generated SQL query in memory
        self.memory.put(ChatMessage(role = "assistant", content = ev.sql))   

        print("\n Generated SQL Query : ", ev.sql)
        
        ctx.write_event_to_stream(ProgressEvent(result = "Generating Response (SQL based Question)"))

        chat_history = self.memory.get()
        chat_history_str = "\n".join([f"{msg.role}: {msg.content}" for msg in chat_history])

        print("\n Chat History : ", chat_history, "\n")

        fmt_messages = self.response_synthesis_prompt.format_messages(
            sql_query = ev.sql,
            context_str = str(retrieved_rows),
            query_str = ev.query,
            chat_history_str = chat_history_str
        )

        # print("\n Formatted Messages : ", fmt_messages, "\n")

        # print('\n Formatted Message : ',fmt_messages)
        
        chat_response = llm.chat(fmt_messages)
        return StopEvent(result=chat_response)


    
    @step
    async def handle_sql_failure(self, ctx : Context, ev : SQLFailureEvent) -> StopEvent:

        ev.iteration_number = ev.iteration_number + 1

        if ev.iteration_number < 4:
            chat_history = self.memory.get()
            chat_history_str = "\n".join([f"{msg.role}: {msg.content}" for msg in chat_history])

            fmt_messages = self.sql_failure_prompt.format_messages(
                query_str = ev.query,
                sql_query_str = ev.sql,
                error = ev.error,
                chat_history_str = chat_history_str,
                table_context_str = ev.table_context_str
            )

            # print(fmt_messages)
            chat_response = self.llm.chat(fmt_messages)
            # print(type(chat_response))
            sql = parse_response_to_sql(chat_response)
            
            return Text2SQLEvent(
                sql = sql,
                query = ev.query,
                table_context_str = ev.table_context_str,
                iteration_number = ev.iteration_number
            )

        else:
            chat_history = self.memory.get()
            chat_history_str = "\n".join([f"{msg.role}: {msg.content}" for msg in chat_history])

            fmt_messages = self.sql_failure_prompt_two.format_messages(
                query_str = ev.query,
                sql_query_str = ev.sql,
                error = ev.error,
                chat_history_str = chat_history_str,
                table_context_str = ev.table_context_str
            )

            # print(fmt_messages)
            chat_response = self.llm.chat(fmt_messages)

            # Store the generated response in memory
            chat_response_str = str(chat_response)[len("assistant: "):].strip()
            self.memory.put(ChatMessage(role = "assistant", content = chat_response_str))   

            return StopEvent(result=chat_response)



    # handler =  new.run(query = "List the products name in descending order, limit 5")


print("\n Welcome to Text to SQL! \n\n")
new = TextToSQLWorkflow(
    obj_retriever = object_retriever,
    sql_retriever = sql_retriever,
    sample_retriever=sample_query_retriever,
    text2sql_prompt = TEXT2SQL_PROMPT,
    response_synthesis_prompt = RESPONSE_SYNTHESIS_PROMPT,
    sql_failure_prompt = SQL_FAILURE_PROMPT,
    sql_failure_prompt_two = SQL_FAILURE_PROMPT_TWO,
    llm = llm,
    query_classification_prompt = QUESTION_CLASSIFICATION_PROMPT,
    general_response_prompt = GENERAL_RESPONSE_PROMPT,
    # verbose = True,
    timeout = 240
)

async def run_workflow(user_query : str) -> str:

    # channel = grpc.aio.insecure_channel('localhost:50051')

    # Your gRPC async code here
    # user_id = input("\nEnter your User ID: ")
    user_id = 12
    # user_query = input("\nEnter your Query: ")

    # Load existing user chat history
    memory = load_chat_history(user_id=user_id, llm=llm)

    # Set the memory in the TextToSQLWorkflow1 instance
    new.memory = memory

    # Run the workflow with the user query
    handler = new.run(query=user_query)

    # Stream the events asynchronously
    async for event in handler.stream_events():
        if isinstance(event, ProgressEvent):
            print(event, flush=True)
            
    # Get the final result
    result = await handler
    print("\nResult:", result)

    # Save the updated chat history
    save_chat_history(user_id=user_id, memory=memory)
    # await channel.close()



    chat_history = memory.get()  

    serialized_history = [
        {"role": msg.role, "content": msg.content} for msg in chat_history
    ]

    # Extract the sql query
    generated_sql_query = serialized_history[-1]["content"] if serialized_history else None


    # CHECK IF IT IS A SQL QUERY OR A GENERAL RESPONSE
    sql_keywords = ["SELECT", "INSERT", "UPDATE", "DELETE", "CREATE", "DROP", "ALTER", "JOIN"]
    
    # Check if any SQL keyword is present anywhere in the string
    if not any(keyword in generated_sql_query for keyword in sql_keywords):
        generated_sql_query = "No SQL query Generated"

    print("\n Generated SQL Query :",generated_sql_query)

    generated_sql_query = generated_sql_query.strip() 

    result = str(result)
    result = result[len('assistant: '):]

    # Return the results
    return result, generated_sql_query


